# Generated by Django 4.2.11 on 2024-04-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BienSo', models.CharField(max_length=100)),
                ('HangXe', models.CharField(max_length=50)),
                ('LoaiXe', models.CharField(max_length=50)),
                ('NamSX', models.IntegerField()),
                ('Color', models.CharField(max_length=10)),
                ('NgayNhap', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='holder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Cardetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Note', models.CharField(max_length=100)),
                ('CarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.car')),
                ('CostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.cost')),
                ('HolderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.holder')),
            ],
        ),
    ]
