# Generated by Django 4.2.11 on 2024-04-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_car_cost_alter_holder_id_cardetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('SDT', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('GhiChu', models.CharField(max_length=100)),
                ('CarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.car')),
            ],
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='CostID',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
