# Generated by Django 4.2.11 on 2024-04-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_oder_alter_cardetail_costid_delete_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GhiChu', models.CharField(max_length=100)),
                ('OderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.oder')),
            ],
        ),
    ]
