# Generated by Django 4.2.11 on 2024-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_oderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HideCost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
