# Generated by Django 4.2.11 on 2024-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_privatesetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
