# Generated by Django 4.2.11 on 2024-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_alter_holder_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
        migrations.RenameField(
            model_name='cardetail',
            old_name='CarID',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='cardetail',
            old_name='CostID',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='cardetail',
            old_name='HolderID',
            new_name='Holder',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='CarID',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='OderID',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='Gia',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
